app/app/main/forms.py
from flask.ext.wtf import Form
from wtforms.fields import StringField, SubmitField
from wtforms.validators import Required
class LoginForm(Form):
    """Accepts a nickname and a room."""
    name = StringField('Name', validators=[Required()])
    room = StringField('Channel Name', validators=[Required()])
    submit = SubmitField('Enter Chatroom')

app/app/__init__.py
from flask import Flask
from flask.ext.socketio import SocketIO

socketio = SocketIO()


def create_app(debug=False):
    """Create an application."""
    app = Flask(__name__)
    app.debug = debug
    app.config['SECRET_KEY'] = 'gjr39dkjn344_!67#'

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    socketio.init_app(app)
    return app

app/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

import routes, events

app/app/main/routes.py
from flask import session, redirect, url_for, render_template, request
from . import main
from .forms import LoginForm
from events import draw
import json

@main.route('/', methods=['GET', 'POST'])
def index():
    """"Login form to enter a room."""
    form = LoginForm()
    if form.validate_on_submit():
        session['name'] = form.name.data
        session['room'] = form.room.data
        return redirect(url_for('.chat'))
    elif request.method == 'GET':
        form.name.data = session.get('name', '')
        form.room.data = session.get('room', '')
    return render_template('index.html', form=form)

@main.route("/draw")
def abc():
    da=draw()
    return json.dumps(da)
@main.route('/chat')
def chat():
    """Chat room. The user's name and room must be stored in
    the session."""
    name = session.get('name', '')
    room = session.get('room', '')
    if name == '' or room == '':
        return redirect(url_for('.index'))
    return render_template('chat.html', name=name, room=room)

app/app/templates/chat.html
<html>
    <head>
        <!--<title>Simple APP: {{ room }}</title>-->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Bluemix Hackathon App</title>
    <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="static/css/bootstrap.min.css">

    <!-- Optional theme -->
        <link rel="stylesheet" href="static/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="static/css/clock.css">
    <!-- Latest compiled and minified JavaScript -->
        <script src="static/js/bootstrap.min.js"></script>
          <script src="https://code.jquery.com/jquery-1.11.2.min.js"></script>
           <script src="static/js/jquery-2.1.3.min.js"></script>
    <script type="text/javascript" src="http://mbostock.github.com/d3/d3.geom.js?2.1.3"></script>
    <script type="text/javascript" src="http://mbostock.github.com/d3/d3.layout.js?2.1.3"></script>
        <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/0.9.16/socket.io.min.js"></script>
        <div id="my"></div>
        <script type="text/javascript" charset="utf-8">
            var data = [{'value': 1, 'label': '#xyz'}, {'value': 1, 'label': '#xy1'}, {'value': 1, 'label': '#xyz12'}]

     
        function abc(data)
        {
            var w = 300,                        
        
    h = 300,                            
    r = 100,                            
    color = d3.scale.category20c();    
        var vis = d3.select("#my")
        .append("svg:svg")              
        .data([data])                   
            .attr("width", w)           
            .attr("height", h)
        .append("svg:g")               
            .attr("transform", "translate(" + r + "," + r + ")")    
     var arc = d3.svg.arc()  
            .outerRadius(r);
     var pie = d3.layout.pie()          
        .value(function(d) { return d.value; });    
     var arcs = vis.selectAll("g.slice")     
        .data(pie)                           
        .enter()                            
            .append("svg:g")                
                .attr("class", "slice");    
        arcs.append("svg:path")
                .attr("fill", function(d, i) { return color(i); } ) 
                .attr("d", arc);                                    
         arcs.append("svg:text")                                     
                .attr("transform", function(d) {                    
                d.innerRadius = 50;
                d.outerRadius = 100;
                return "translate(" + arc.centroid(d) + ")";        
            })
            .attr("text-anchor", "middle")                          
            .text(function(d, i) { return data[i].label; });
        }
       // abc(data);
            var socket;
            var clients=[];
            $(document).ready(function(){
                socket = io.connect('http://' + document.domain + ':' + location.port + '/chat');
                socket.on('connect', function() {
                    socket.emit('joined', {});
                    clients.push(socket.id);
                    socket.emit('notify',{});
                });
                socket.on('notify', function(data) {
            //alert("hello");
                    $('#notify').append(data.msg + '\n');
                    $('#notify').scrollTop($('#notify')[0].scrollHeight);
                   // socket.connected[clients[1]].emit("individual","Hello");
                });
                socket.on('status', function(data) {
                    $('#entered').html( '<b style="color:red;"> ' + data.msg + '</b>');
                    $('#entered').scrollTop($('#entered')[0].scrollHeight);
                });
                socket.on('message', function(data) {
                    $('#chat').append(data.msg + '</br>');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
                });
                socket.on('draw',function(data)
                {
                    d=JSON.parse(data.msg)
                    console.log(d);
                    abc(d);
                });
                $('#text').keypress(function(e) {
                    var code = e.keyCode || e.which;
                    if (code == 13) {
                        text = $('#text').val();
                        $('#text').val('');
                        socket.emit('text', {msg: text});
                    }
                });
            });
               
        </script>
        <style>
            
        </style>
    </head>
    <body>
                <div class="container" style="height: 60px; background-color: #660066; width: 100%;>
            <div class="row"">
                <div class="col-md-4"><h2 style="color: white;margin-bottom: 5px;vertical-align: middle">{{ room }}<span> Channel</span></h3></div>
                <div class="col-md-8"></div>
            </div>
        </div>
        
        <div class="container">  <!-- Container 1 -->
            <div class="col-md-3">
                <div id="n" style="height: 30%">
                <div style="font-size:18px;width: 70%;color: white; background-color: #ff6600; text-align: center; margin-top:40px;height: 30px;padding-top:4px">Trending Now:</div>
                <div id="notify" style="overflow: auto;height: 100%;width: 70%"></div>
                </div>
            </div>
            <div class="col-md-6" style="margin-left: -40px; margin-top: 20px;border-radius: 15px">
                <div id="entered"></div>
            <div id="chat" style="letter-spacing: 1px;height:60%;width:100%; overflow: auto;"></div></div>
            <div class="col-md-3">              <!--  ________________________clock Event_____________________ -->
                <div class="outer_face">
                    <div class="marker oneseven"></div>
                    <div class="marker twoeight"></div>
                    <div class="marker fourten"></div>
                    <div class="marker fiveeleven"></div>
<!-- _______________Inner Face_______________ -->                    
                    <div class="inner_face">
                        <div class="hand hour"></div>
                        <div class="hand minute"></div>
                        <div class="hand second"></div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="container" style="margin-top: 20px">
            <div class="col-md-3"><button class="btn btn-danger"><a href="{{ url_for('main.index') }}" onclick="socket.emit('left', {});" style="width: 90%; height: 30px; font-size: 18px; text-decoration: none;color: white">Leave this Channel</a></button></div>
            <div class="col-md-6" style="margin-left: -40px">
            <input id="text" placeholder="   Enter your message here" style="letter-spacing: 1px;width: 100%;margin-left: 0%; font-size: 16px;height: 50px; border: 3px solid #660066; border-radius: 10px">
            </div>
            <div class="col-md-3"></div>
        </div>
        
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

    <script type="text/javascript">

    var $hands = $('    div.hand')

    window.requestAnimationFrame = window.requestAnimationFrame
                               || window.mozRequestAnimationFrame
                               || window.webkitRequestAnimationFrame
                               || window.msRequestAnimationFrame
                               || function(f){return setTimeout(f, 1000/60)}


    function updateclock(){
     var curdate = new Date()
     var hour_as_degree = ( curdate.getHours() + curdate.getMinutes()/60 ) / 12 * 360
     var minute_as_degree = curdate.getMinutes() / 60 * 360
     var second_as_degree = ( curdate.getSeconds() + curdate.getMilliseconds()/1000 ) /60 * 360
     $hands.filter('.hour').css({transform: 'rotate(' + hour_as_degree + 'deg)' })
     $hands.filter('.minute').css({transform: 'rotate(' + minute_as_degree + 'deg)' })
     $hands.filter('.second').css({transform: 'rotate(' + second_as_degree + 'deg)' })
     requestAnimationFrame(updateclock) // 
    }

    requestAnimationFrame(updateclock)


</script>
    </body>
</html>

app/app/templates/index.html
<html>
    <head>
         <meta charset="utf-8">
             <meta name="viewport" content="width=device-width, initial-scale=1">
                <title>Bluemix Hackathon App</title>
    <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="static/css/bootstrap.min.css">

    <!-- Optional theme -->
        <link rel="stylesheet" href="static/css/bootstrap-theme.min.css">

    <!-- Latest compiled and minified JavaScript -->
        <script src="static/js/bootstrap.min.js"></script>
        <script src="static/js/jquery-2.1.3.min.js"></script>
        <style>
        .myName{
            letter-spacing: 1px;float: right;opacity: 1;color:black;height: 40px; border-radius: 10px; border: 1px solid #33cccc;margin-bottom: 15px;margin-top: 5px;margin-right: 20px;
        }
        .myChannel{
            letter-spacing: 1px;color:black;float: right;height: 40px;opacity: 1; border-radius: 10px; border: 1px solid #33cccc;margin-bottom: 15px;margin-top: 5px;margin-right: 20px;
        }
            .cover-page {
                animation-name: bgcolour;
                animation-duration: 5s;
                animation-iteration-count: infinite;
                animation-direction: alternate;
                -webkit-animation-name: bgcolour;
                -webkit-animation-duration: 8s;
                -webkit-animation-iteration-count: infinite;
                -webkit-animation-direction: alternate;
            }
            @keyframes bgcolour {
                0% {background-color: #000066}
                25% {background-color: #cc33ff}
                50% {background-color: #ff9933}
                75% {background-color: #0099ff}
            }
            @-webkit-keyframes bgcolour {
                 0% {background-color: #000066}
                25% {background-color: #cc33ff}
                50% {background-color: #ff9933}
                75% {background-color: #0099ff}    
            }
            .slideshow {
                position: absolute;
                width: 100%;
                z-index: -199;
            }
            .slideshow figure {
                margin: 0;
            }
            #vid {
                z-index: -399;
                width: 1550px;
                height: 750px;
                margin-top: 60px;
                position: fixed;
                margin-left: -15%;
            }
            .channel-form {
                width: 100%;
                background-color: #ccffcc;
                position: inherit;
                height: auto;
            }
            .form-ctrl:hover {
                opacity: 0.9;
            }
            .myButton{
                border-radius: 8px; background-color: #3366ff; opacity: 2;;margin-top: 30px;width: 100%;height: 40px; letter-spacing: 1px; font-size: 20px;color:white;
            }
            .formClass
            {
                margin: 20px; font-size: 18px;color: white;
                margin-top: 5px;
            }
        /*             
            .outer_face {
                position: relative;
                width: 250px;
                height: 250px;
                border-radius: 250px;
                background: white;
                box-shadow: inset 0 0 10px gray;
                border: 14px solid black
            }

            .outer_face::before, .outer_face::after{ /* 12-6 and 9-3 hour markers 
                content: "";
                position: absolute;
                width: 10px;
                height: 100%;
                background: black;
                z-index: 0;
                left: 50%;
                margin-left: -5px;
                top: 0
            }
.outer_face::after { /* 9-3 time marker specifically
-moz-transform: rotate(90deg);
-ms-transform: rotate(90deg);
-webkit-transform: rotate(90deg);
transform: rotate(90deg)
}
            */
            
            
            
        </style>
    </head>
    <body>
        <div style="width: 100%">
            <div class="container cover-page" style="z-index: -9;cursor: pointer;opacity: 0.8;background-color: #000066; width: 100%; height: 100%; max-height: 700px">
                <div class="row" style="margin-top: 20%">
                <div class="col-md-4"></div>
                <div class="col-md-4" style="margin-left: 50px; opacity: 1">
                <h2 style="font-weight: 500;margin-left: 40px; color: #fff; font-size: 24px">Welcome to</h2>
                <h1 style="color: #fff; font-weight: 800; margin-left: 20px; font-size: 48px">Talkout</h1>
                </div>
                <div class="col-md-4"></div>
                </div>
            </div>    
        </div>
        
         <div class="container navb" id="header" style="width: 100%;z-index: -99;position: fixed; background-color: #660066; height: 10%; top:0">
            <div class="col-md-3">
		<div class="logo" style="width: 90%;margin-left: 10px; opacity: 0.8">
        	    <a href="index.html">
			<h2 style="color: #fff; font-weight: 300">Workspace</h2>
        	    </a>
    		</div>
	    </div>
            <div class="col-md-9">
                <div class="outer_face">
                    
                </div>
            </div>
        </div>
       
       <div class="container"> 
        <video id="vid" width="200" autoplay loop muted>
        <source src="static/images/website_bg.mp4" type="video/mp4"></source>
        </video>
        </div>
       
       <div class="container">
        <div class="row" style="margin-top:23%;">
            <div class="col-md-4"></div>
            <div class="col-md-4 form-ctrl" style="margin-left: 27%;width: 450px;border-radius: 30px; background-color: #0f3d3d;opacity: 0.7; height: 300px; position: fixed">
                <h1 style="letter-spacing: 1px; color: white; font-family: helvetica;text-align: center;font-weight: 600">Enter WorkSpace</h1>
                <form  method="post" style="">
                    
            {{ form.hidden_tag() }}
            {{ form.name.label(class_="formClass") }}: {{ form.name(class_="myName",placeholder="Enter Name",value="") }} {% for error in form.name.errors %}{{ error }}{% endfor %}<br>
            <br style="clear: both">
            {{ form.room.label(class_="formClass") }}: {{ form.room(class_="myChannel",placeholder="Enter Channel",value="") }} {% for error in form.room.errors %}{{ error }}{% endfor %}<br>
            {{ form.submit(class_="myButton") }}
                    <!--<div style="margin: 20px; font-size: 18px;color: white">
                        Channel Name  <input type="text" name="channel_name" placeholder="   Enter Channel Name" style="letter-spacing: 1px;color:black;float: right;height: 40px;opacity: 1; border: 1px solid #33cccc;margin-bottom: 15px;margin-top: -5px">
                        <br style="clear: both">
                        Name  <input type="text" name="name" placeholder="   Enter your name" style="letter-spacing: 1px;float: right;opacity: 1;color:black;height: 40px; border: 1px solid #33cccc;margin-bottom: 15px;margin-top: -5px">
                        <br style="clear: both">
                        Email  <input type="text" name="email" placeholder="   Enter your name" style="letter-spacing: 1px;float: right;opacity: 1;color:black;  height: 40px; border: 1px solid #33cccc;margin-bottom: 15px;margin-top: -5px">
                        <br style="clear: both">
                        <button type="button" value="submit" style="border-radius: 8px; background-color: #3366ff; opacity: 2;;margin-top: 10px;width: 100%;height: 40px; letter-spacing: 1px; font-size: 20px">Enter</button>
                    </div>-->
                </form>
            </div>
        </div>
        </idv>
    <!--
        <div class="container" style="height: 640px; background-color: ##33ad33; position: relative">
            
        </div>
        
        <div class="container channel-form" id="form">
            <div class="row cont-2">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                    <form>
                        <div>
                            Channel Name :<input type="text" name="channel_name" placeholder="Enter Channel name">
                            Name : <input type="text" name="name" placeholder="Enter your name">
                            <button type="button" value="submit">Submit</button>
                        </div>
                    </form>
                </div>
                <div class="col-md-3"></div>
            </div>
        </div>        
                
 -->       
        <div class="footer" style="height: 6%;margin-top:90%; margin-bottom: 0px;z-index: -9999">
            <div class="row">
            <div class="col-md-4" style="color: white; font-size: 16px; font-weight: 300">
            &copy;
            </div>
            </div>
        </div>
        <!--
        <h1>Hacker Room-Chat</h1>
        
        <form method="POST">
            {{ form.hidden_tag() }}
            {{ form.name.label }}: {{ form.name() }} {% for error in form.name.errors %}{{ error }}{% endfor %}<br>
            {{ form.room.label }}: {{ form.room() }} {% for error in form.room.errors %}{{ error }}{% endfor %}<br>
            {{ form.submit() }}
        </form>
        -->
        <script>
            $(window).scroll(function(){
                if ($(this).scrollTop()>0) {
                    //code
                    $('.cover-page').fadeOut();
                    $('.navb').fadeIn();
                }
                /*else{
                    $('.cover-page').fadeIn();
                }*/
                });
        </script>
    </body>
</html>